"""room player ready flag

Revision ID: 00aafe69b479
Revises: 6adf28fc88fa
Create Date: 2026-08-27 06:27:54.176190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00aafe69b479'
down_revision = '6adf28fc88fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ready', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_players', schema=None) as batch_op:
        batch_op.drop_column('ready')

    # ### end Alembic commands ###
